name: Cleanup Workflow Runs
on:
  workflow_dispatch: # Allows manual triggering

jobs:
  delete-runs:
    runs-on: windows-latest
    steps:
      - name: Delete old workflow runs
        uses: actions/delete-workflow-runs@v2
        with:
          retain_days: 1 # Delete runs older than 1 day
          keep_minimum_runs: 5 # Always keep at least 5 run